#!/bin/bash

export JEKYLL_ENV=development
bundle install --no-deployment --path vendor/bundle
# Run this command if you need to bump up Gem versions
# bundle update
bundle exec jekyll serve --trace --config '_config.yml,_config.dev.yml'
